### ISSUE TITLE
Packages for RPM and DEB

### ISSUE THREAD

**Issue by KevinAtSesam** [aws/aws-lc#804]
### Problem:

By providing your own OpenSSL implementation in source only, you make it very hard for end-users to integrate your library in their own tooling. For example, I would have to manually compile the project multiple times for different architectures, since my company uses quite a few containers. In the end we all run it on EC2, but this just adds unnecessary hoops just to have [ACCP](https://github.com/corretto/amazon-corretto-crypto-provider) support.

### Solution:

It would be great if you can provide .rpm and .deb packages with repositories. Preferably tested for RHEL, CentOS Stream, and Ubuntu. Ideally down-streamed and integrated with their respective ecosystems.

* **Does this change any public APIs?** No
* **Which algorithm(s) will this impact?** None

### Requirements / Acceptance Criteria:

What must a solution address in order to solve the problem? How do we know the solution is complete?

* Auto-build system for .rpm and .deb packages
  * Validation on selected platforms
* Repository for distribution
  * GPG signed and all
* Upstream specs
  * Fedora Linux and Debian Sid preferably
* Update documentation

### Bootnote

OpenSSL, BoringSSL, GnuTLS and WolfSSL all have their packages for major distributions, which provides a whole series of benefits: 
- Users can get their security updates from a single source, 
- it's integrated with existing tooling,
- it works on more architectures, 
- and more feedback can be gathered from the entire user base.

Don't deny yourself those benefits

**Comment by andrewhop** [comment]
Hi, thanks for the feedback and interest in AWS-LC. I see your initial concern with ACCP's use in https://github.com/corretto/amazon-corretto-crypto-provider/issues/269 has been resolved (ACCP bundles AWS-LC for it's customers).

We've looked into adding support for Amazon Linux (internal references: CryptoAlg-792 and /CryptoAlg-1069) but not other distributions. What is the best way to let customers consume AWS-LC? If we install AWS-LC as libcrypto.so to `/lib/x86_64-linux-gnu/`  (for Ubuntu) we will conflict with other libcrypto.so's (e.g. OpenSSL). If we install with a different name or in a subfolder it is harder to consume AWS-LC because other libraries to update their build to find/handle the different path. Which of these did you have in mind? Do you have another idea that would make it easy to consume AWS-LC?

Looking at Ubuntu 22.04:
* libssl-dev (OpenSSL) -> `/usr/lib/x86_64-linux-gnu/libcrypto.so`
* libwolfssl-dev -> `/usr/lib/x86_64-linux-gnu/libwolfssl.so`
* BoringSSL -> I can't find this
* android-libboringssl -> `/usr/lib/x86_64-linux-gnu/android/libcrypto.so.0`

W are focusing on making it easier to consume AWS-LC through other higher level libraries that do the bundling for us (e.g. ACCP).

**Comment by KevinAtSesam** [comment]
> This issue has not received a response in 1 week. If you want to keep this issue open, please just leave a comment below and auto-close will be canceled.

Closing issues does not resolve them. I recommend against bots like these since you'll just end up with worse issue tracking and duplicates.

---

On topic, yes, my primary problem has been resolved and I've helped clarifying the documentation. 

As for helping customers use it; It's a chicken-and-egg problem, because you can't just drop-in-and-replace an existing implementation. This is a known problem with GnuTLS and BoringSSL as well. You do have one benefit over these two though, since you already have one application(-library) that uses it.

For now, I think the best cause of action, would be to create a Debian Sid and Fedora Linux package downstream. If you have the resources to maintain these, future version of AWS-LC can use the native package of CentOS or Ubuntu in the future.

**Comment by skmcgrail** [comment]
Hey @KevinAtSesam

RPM and/or DEB packages are potential distribution mechanisms that we are considering for easing the integration story for developers looking to use AWS-LC. At this time though we don't have anything more specific that we can share in terms of timelines or a public roadmap, but we are tracking such an ask within our internal process planning.

I am going to move to close this issue, as we prefer to keep our set of open GitHub issues limited to bug reports and feature request that we are looking to implement in the near term (or are open to outside contributions). We appreciate you taking the time to open this feature request and to share with us your input and general use cases for such a feature.
